name: "Deploy"
 
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
permissions:
  contents: read

env:
  AWS_PROFILE: default
  AWS_REGION: us-east-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_assume_role_arn: ${{ secrets.TF_VAR_assume_role_arn }}
  STAGE: ${{ (github.ref == 'refs/heads/main' && github.event_name == 'push') && 'prod' || 'stg' }}
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
 
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get terraform version
        id: get-terraform-version
        shell: bash
        run: echo "terraform-version=$(cat .terraform-version)" >> $GITHUB_OUTPUT

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ steps.get-terraform-version.outputs.terraform-version }}

      - name: Terraform Format
        run: cd terraform && terraform fmt -recursive

      - name: Configure AWS Profile
        run: make configure-aws-profile

      - name: Terraform Init
        run: cd terraform && terraform init

      - name: Get Docker Image Tag
        id: docker_image_tag
        run: make get-docker-image-tag

      - name: Setup ECR Repository
        run: make setup-ecr-repository

      - name: Build Docker Image
        run: docker build --platform linux/amd64 --provenance false -f Dockerfile -t job:${{ env.IMAGE_VERSION }} .

      - name: Docker Login
        run: make docker-login

      - name: Docker Tag
        run: docker tag job:${{ env.IMAGE_VERSION }} ${{ env.ECR_REPOSITORY_URL }}:${{ env.IMAGE_VERSION }}

      - name: Push Docker Image
        run: docker push ${{ env.ECR_REPOSITORY_URL }}:${{ env.IMAGE_VERSION }}

      - name: Terraform Plan
        run: cd terraform && terraform plan

      - name: Terraform Deploy
        if: ${{ env.STAGE == 'stg' }}
        run: cd terraform && terraform apply -auto-approve

      - name: Docker Purge
        if: ${{ env.STAGE == 'prod' }}
        run: make docker-purge